import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import Navbar from '../components/nav'
import SectionCards from '../components/section-cards'
import {
    getPopularVideos,
    getVideos,
    getWatchedAgainVideos,
} from '../lib/videos'
import { redirectUser } from '../utils/redirectUser'

export async function getServerSideProps(context) {
    const { userId, token } = await redirectUser(context)
    if (!userId) {
        return {
            props: {},
            redirect: {
                destination: '/login',
                permanent: false,
            },
        }
    }
    const disneyVideos = await getVideos({ searchQuery: 'disney trailer' })
    const productivityVideos = await getVideos({
        searchQuery: 'productivity',
    })
    const travelVideos = await getVideos({ searchQuery: 'indie music' })
    const popularVideos = await getPopularVideos()
    const watchItAgainVideos = await getWatchedAgainVideos(token, userId)

    return {
        props: {
            disneyVideos,
            productivityVideos,
            travelVideos,
            popularVideos,
            watchItAgainVideos,
        },
    }
}

export default function Home({
    disneyVideos = [],
    productivityVideos = [],
    travelVideos = [],
    popularVideos = [],
    watchItAgainVideos = [],
}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Netflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <Navbar />
                <Banner
                    title="Kill Bill"
                    subTitle="Awesome movie"
                    imgUrl="/static/banner.png"
                    videoId="mYfJxlgR2jw"
                />
                <div className={styles.sectionWrapper}>
                    <SectionCards
                        title="Disney"
                        videos={disneyVideos}
                        size="large"
                    />
                    <SectionCards
                        title="Watch it again"
                        videos={watchItAgainVideos}
                        size="small"
                    />
                    <SectionCards
                        title="Travel"
                        videos={travelVideos}
                        size="small"
                    />
                    <SectionCards
                        title="Productivity"
                        videos={productivityVideos}
                        size="medium"
                    />
                    <SectionCards
                        title="Popular"
                        videos={popularVideos}
                        size="small"
                    />
                </div>
            </div>
        </div>
    )
}
